/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PeopleLazyImport = createFileRoute('/people')()
const MinorsLazyImport = createFileRoute('/minors')()
const EmploymentLazyImport = createFileRoute('/employment')()
const DegreesLazyImport = createFileRoute('/degrees')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PeopleLazyRoute = PeopleLazyImport.update({
  path: '/people',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/people.lazy').then((d) => d.Route))

const MinorsLazyRoute = MinorsLazyImport.update({
  path: '/minors',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/minors.lazy').then((d) => d.Route))

const EmploymentLazyRoute = EmploymentLazyImport.update({
  path: '/employment',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/employment.lazy').then((d) => d.Route))

const DegreesLazyRoute = DegreesLazyImport.update({
  path: '/degrees',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/degrees.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/degrees': {
      preLoaderRoute: typeof DegreesLazyImport
      parentRoute: typeof rootRoute
    }
    '/employment': {
      preLoaderRoute: typeof EmploymentLazyImport
      parentRoute: typeof rootRoute
    }
    '/minors': {
      preLoaderRoute: typeof MinorsLazyImport
      parentRoute: typeof rootRoute
    }
    '/people': {
      preLoaderRoute: typeof PeopleLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  DegreesLazyRoute,
  EmploymentLazyRoute,
  MinorsLazyRoute,
  PeopleLazyRoute,
])

/* prettier-ignore-end */
